server:
  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: ${MYSQL_USER:-spotisee}
  password: ${MYSQL_PASSWORD:-spotisee-password}
  url: jdbc:mysql://database:3306/${MYSQL_DATABASE:-Spotisee}?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
  maxSize: 10