server:
  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?ssl-mode=REQUIRED&serverTimezone=UTC&allowPublicKeyRetrieval=true
  maxSize: 10

logging:
  level: INFO

  loggers:
    com.mycompany.app: INFO
    org.glassfish.jersey.server: DEBUG
    org.hibernate.SQL: DEBUG
    org.jdbi.v3.core.statement: DEBUG